#!/bin/zsh

# options
local db=:server:nosql:default
local port=5050
while getopts d:p:q name
do
    case $name in
        d) db=:server:nosql:$OPTARG ;;
        p) port=$OPTARG ;; # checking for numerics is for losers
        q) (( quietflag++ )) ;;
    esac
done

# init
zmodload zsh/net/tcp
ztcp -l $port
local fd=$REPLY
trap "ztcp -c $fd"

args=(-d $db)

while [ 1 ]
do
    ztcp -a $fd
    ./handler $args -f $REPLY &
done
